---
title: "testing_eval"
author: "DWH"
date: "2026-04-07"
output: html_document
---


## packages and functions 

```{r}
library(tidyverse)
library(RHESSysIOinR)

#functions 
source("../read_plot_rhessys_fun.R")

#read in validation csv
target_df <- read_csv("../Target_Data_comp/TargetData_15mar26.csv") |> 
  rename(date = Date)

```






#Spin and test

```{r}
devpath <- "C:/Users/dwh18/OneDrive/Desktop/R_Projects/RHESSys_development/RHESSys_Tutorial/HPB_files_NewMaps/"
```


```{r}
##spin

# read_plot_rhessys(outname = paste0(devpath, "out/apr13RouteTest/COWTest1/hpb_spin_1cow"), 
#                   date_filter = as.Date("1960-01-01"), ncol = 5, validate = F)


read_plot_rhessys(outname = paste0(devpath, "out/apr13RouteTest/COWTest3/hpb_spin_4cow"), 
                  date_filter = as.Date("1960-01-01"), ncol = 5, validate = F)


## validate
read_plot_rhessys(outname = paste0(devpath, "out/apr13RouteTest/COWTest3/hpb_test_4cow"), ncol = 5, validate = T)

read_plot_rhessys(outname = paste0(devpath, "out/apr13RouteTest/COWTest3/hpb_test_4cow_noSR"), ncol = 5, validate = T)

##routing

##read in streamrouting 
# col_names <- c("day","month","year","reachID","Qout","lateralinput","Qin","waterdepth","reservoir.store","NO3_out","NH4_out","DON_out","DOC_out")

df <- read.table(paste0(devpath, "out/apr13RouteTest/COWTest3/hpb_test_4cow_streamrouting.daily"),
                 header = TRUE)
head(df)

df |> 
  mutate(date = ymd(paste(year, month, day, sep = "-"))) |> 
  select(date, everything()) |> 
  pivot_longer(-c(1:5)) |> 
  ggplot(aes(x = date, y = value, color = as.factor(reachID)))+
  geom_point()+ facet_wrap(~name, scales = "free_y")+ theme_bw()

```


```{r}
#n-cycle validate
zz <- readin_rhessys_output(paste0(devpath, "out/apr13RouteTest/COWTest3/hpb_test_4cow"))
# zz <- readin_rhessys_output(paste0(devpath, "out/apr13RouteTest/COWTest1/hpb_test_1cow")) #when gw and stream ~ =

zz$bdg |> dplyr::select(date, #year,
                        gwNO3out, streamflow_NO3
                        # N_dep, nuptake, nfix, nitrif, denitrif, #rates
                        # gwDONout, gwNH4out, gwNO3out #fluxes
                        # #stocks
                        # ,plantn, soiln,
                        # nitrate, sminn, surfaceN, npool, litrn,
                        # gwDON, gwNH4, gwNO3, streamflow_NO3, streamflow_NH4, streamflow_DON,
                        # StreamNO3_from_surface, StreamNO3_from_sub
                        ) |> 
  mutate(stream_gwNO3out = streamflow_NO3 - gwNO3out) |> 
  pivot_longer(-1) |> 
  ggplot(aes(x = date, y = value))+
  geom_point()+
  facet_wrap(~name, scales = "free_y")


# zed <- readLines(paste0(devpath, "out/apr13RouteTest/COWTest3/hpb_test_3cow_grow_basin.daily"))

##test drop off timing
# zzzzz <- N_grow |> dplyr::select(date, year, plantc) |>   
#   ggplot(aes(x = date, y = plantc))+  geom_point()
# 
# zzzzz
# plotly::ggplotly(zzzzz)

# zzz <- readin_rhessys_output(paste0(devpath, "out/apr13RouteTest/COWTest1/hpb_spin_1cow"))
# N_grow2 <- zzz$bdg
# 
# zzzzz <- N_grow2 |> dplyr::select(date, year, plantc) |>   
#   filter(date > ymd("2000-01-01"),
#          date < ymd("2050-01-01")) |> 
#   ggplot(aes(x = date, y = plantc))+  geom_point()
# 
# zzzzz
# plotly::ggplotly(zzzzz)

```













## Look at patches 


```{r}






```




























## Look at basin level output for with stream routing vs without


```{r}
devpath <- "C:/Users/dwh18/OneDrive/Desktop/R_Projects/RHESSys_development/RHESSys_Tutorial/HPB_files_NewMaps/"
```


#small patch tes

```{r}
read_plot_rhessys(outname = paste0(devpath, "out/SmallPatch/RouteTest100yr/hpb_RouteTests"), 
                  date_filter = as.Date("1960-01-01"), ncol = 5, validate = F)

##read in streamrouting 
col_names <- c("day","month","year","reachID","Qout","lateralinput","Qin","waterdepth","reservoir.store","NO3_out","NH4_out","DON_out","DOC_out")

df <- read.table(paste0(devpath, "out/SmallPatch/RouteTest100yr/hpb_RouteTests_streamrouting.daily"),
                 header = TRUE, col.names = col_names, fill = TRUE)
head(df)

df |> 
  mutate(date = ymd(paste(year, month, day, sep = "-"))) |> 
  select(date, everything()) |> 
  pivot_longer(-c(1:5)) |> 
  ggplot(aes(x = date, y = value, color = as.factor(reachID)))+
  geom_point()+ facet_wrap(~name, scales = "free_y")+ theme_bw()

```




# ROUTING V NO ROUTING alt cut patches

```{r}
#with routing

# dat = readin_rhessys_output(outname)
# z <- dat$bd
read_plot_rhessys(outname = paste0(devpath, "out/RouteTest100yr/hpb_RouteTest_1"), 
                  date_filter = as.Date("1960-01-01"), ncol = 5, validate = F)


#no routing 
read_plot_rhessys(outname = paste0(devpath, "out/RouteTest100yr/hpb_RouteTest_NOROUTE"), 
                  date_filter = as.Date("1960-01-01"), ncol = 5, validate = F)

##read in streamrouting 
col_names <- c("day","month","year","reachID","Qout","lateralinput","Qin","waterdepth","reservoir.store","NO3_out","NH4_out","DON_out","DOC_out")

df <- read.table("C:/Users/dwh18/OneDrive/Desktop/R_Projects/RHESSys_development/RHESSys_Tutorial/HPB_files_NewMaps/out/RouteTest100yr/hpb_RouteTest_1_streamrouting.daily",
                 header = TRUE, col.names = col_names, fill = TRUE)
head(df)

df |> 
  mutate(date = ymd(paste(year, month, day, sep = "-"))) |> 
  select(date, everything()) |> 
  pivot_longer(-c(1:5)) |> 
  ggplot(aes(x = date, y = value, color = as.factor(reachID)))+
  geom_point()+ facet_wrap(~name, scales = "free_y")+ theme_bw()

```


















